noun_0 = input("Enter a noun: ")
pl_noun_1 = input("Enter a plural noun: ")
noun_1 = input("Enter a noun: ")
pl_noun_2 = input("Enter a plural noun: ")
pl_noun_3 = input ("Enter a plural noun: ")
adj_1 = input("Enter an adjective: ")
verb_1 = input("Enter a verb: ")
verb_2 = input("Enter a verb: ")
adv_1 = input("Enter an adverb: ")
verb_3 = input("Enter a verb: ")
verb_4 = input("Enter a verb: ")
adv_2 = input("Enter an adverb: ")
noun_4 = input("Enter a noun: ")
noun_5 = input("Enter a noun: ")
verb_5 = input ("Enter a verb: ")
num = input ("Enter a number: ")

print("Here is your story:\n\nHow to Bake a "+noun_0+" Cake\n\nFirst, gather your "+pl_noun_1+". You will need a "+noun_1+", two "+pl_noun_2+",\nhalf a cup of "+noun_0+", and a few "+pl_noun_3+". Be sure that\nthe "+noun_1+" is very "+adj_1+". Take the "+noun_1+" and "+verb_1+" it into\nthe "+noun_0+". "+verb_2+" the "+noun_0+" "+adv_1+". Then, "+verb_3+" the "+pl_noun_3+" with\na "+noun_4+". Combine the "+pl_noun_2+", "+noun_1+", "+pl_noun_3+", and "+noun_0+", and\n"+verb_4+" "+adv_2+". Pour into a "+noun_5+" and "+verb_5+" for "+num+" minutes.\nYour "+noun_0+" cake is now ready to serve!")